-- EverQuest-inspired custom spell pack (draft-pool registration).
-- GENERATED by tools/build_client_patch.py from tools/eq_spell_pack.json.
-- Do not edit by hand.
--
-- The spells themselves live in the patched Spell.dbc shipped by
-- wow-client/Data/patch-P.mpq (client) and dbc/Spell.dbc (server, deployed
-- by install.sh). These tables only make them visible to the draft picker.

DELETE FROM `dbc_skillline` WHERE `ID` = 999;
INSERT INTO `dbc_skillline` (`ID`, `CategoryID`, `DisplayName_Lang_enUS`) VALUES
    (999, 7, 'Forgotten Tomes');

DELETE FROM `dbc_skilllineability` WHERE `Spell` IN (993001, 993002, 993003, 993004, 993005, 993006, 993007, 993008, 993009, 993010, 993011, 993012, 993013, 993014, 993015, 993016, 993017, 993018, 993019, 993020, 993021, 993022, 993023, 993024, 993025, 993026, 993027, 993028, 993029, 993030, 993031, 993032, 993033, 993034, 993035, 993036);
INSERT INTO `dbc_skilllineability` (`ID`, `SkillLine`, `Spell`, `RaceMask`, `ClassMask`) VALUES
    (1100000, 999, 993001, 0, 0),
    (1100001, 999, 993002, 0, 0),
    (1100002, 999, 993003, 0, 0),
    (1100003, 999, 993004, 0, 0),
    (1100004, 999, 993005, 0, 0),
    (1100005, 999, 993006, 0, 0),
    (1100006, 999, 993007, 0, 0),
    (1100007, 999, 993008, 0, 0),
    (1100008, 999, 993009, 0, 0),
    (1100009, 999, 993010, 0, 0),
    (1100010, 999, 993011, 0, 0),
    (1100011, 999, 993014, 0, 0),
    (1100012, 999, 993015, 0, 0),
    (1100013, 999, 993016, 0, 0),
    (1100014, 999, 993017, 0, 0),
    (1100015, 999, 993019, 0, 0),
    (1100016, 999, 993021, 0, 0),
    (1100017, 999, 993022, 0, 0),
    (1100018, 999, 993023, 0, 0),
    (1100019, 999, 993024, 0, 0),
    (1100020, 999, 993025, 0, 0),
    (1100021, 999, 993026, 0, 0),
    (1100022, 999, 993027, 0, 0),
    (1100023, 999, 993028, 0, 0),
    (1100024, 999, 993029, 0, 0),
    (1100025, 999, 993030, 0, 0);

DELETE FROM `dbc_spells` WHERE `ID` IN (993001, 993002, 993003, 993004, 993005, 993006, 993007, 993008, 993009, 993010, 993011, 993012, 993013, 993014, 993015, 993016, 993017, 993018, 993019, 993020, 993021, 993022, 993023, 993024, 993025, 993026, 993027, 993028, 993029, 993030, 993031, 993032, 993033, 993034, 993035, 993036);
INSERT INTO `dbc_spells`
    (`ID`, `Category`, `Attributes`, `MaxLevel`, `SpellLevel`, `DurationIndex`,
     `Effect_1`, `Effect_2`, `Effect_3`, `SpellIconID`, `Rarity`,
     `Name_Lang_enUS`, `Description_Lang_enUS`) VALUES
    (993001, 0, 0, 0, 8, 3, 6, 0, 0, 163, 1, 'Ensnare', 'Snares the target, reducing movement speed by 55% for $d.'),
    (993002, 0, 0, 0, 20, 5, 6, 0, 0, 199, 2, 'Forlorn Deeds', 'The target\'s attack speed is reduced by 50% for $d.'),
    (993003, 0, 0, 0, 30, 31, 6, 0, 0, 199, 3, 'Color Slant', 'A blinding lattice of colour stuns all nearby enemies for $d.'),
    (993004, 0, 0, 0, 40, 5, 6, 0, 0, 1500, 4, 'Charm', 'Bends the target to your will, forcing it to serve you for $d.'),
    (993005, 0, 0, 0, 25, 9, 6, 6, 0, 234, 2, 'Engulfing Darkness', 'Shadow clings to the target, slowing movement by 50% and dealing damage over $d.'),
    (993006, 0, 0, 0, 15, 29, 2, 6, 0, 313, 1, 'Envenomed Bolt', 'Hurls a bolt of venom for instant damage, then poisons the target for $d.'),
    (993007, 0, 0, 0, 12, 26, 6, 0, 0, 20, 2, 'Enduring Roots', 'Roots the target in place for $d.'),
    (993008, 0, 0, 0, 18, 26, 6, 6, 0, 96, 2, 'Mesmerize', 'Mesmerizes the target, preventing all action but making it invulnerable for $d.'),
    (993009, 0, 0, 0, 10, 9, 6, 0, 0, 454, 1, 'Harmony', 'Calms the target, preventing it from attacking for $d.'),
    (993010, 0, 0, 0, 20, 41, 28, 0, 0, 61, 3, 'Cavorting Bones', 'Animates a skeletal servant to fight for you for $d.'),
    (993011, 0, 0, 0, 30, 42, 6, 6, 0, 208, 3, 'Lich', 'Your flesh withers, draining your health to fuel your mana regeneration. Lasts $d.'),
    (993014, 0, 0, 0, 25, 30, 6, 0, 0, 515, 2, 'Alacrity', 'Quickens your hands, increasing attack speed by 40% for $d.'),
    (993015, 0, 0, 0, 20, 42, 6, 0, 0, 685, 2, 'Aegolism', 'Shields the caster in ancient wards, increasing health by 1000 for $d.'),
    (993016, 0, 0, 0, 45, 41, 6, 6, 6, 332, 4, 'Avatar', 'The strength of the gods fills you, greatly increasing melee power for $d.'),
    (993017, 0, 0, 0, 25, 30, 6, 0, 0, 220, 3, 'Spirit of the Puma', 'The spirit of the great cat rides your weapon, striking for extra damage. Lasts $d.'),
    (993019, 0, 0, 0, 35, 30, 6, 0, 0, 546, 3, 'Shroud of the Leech', 'Your strikes drain the life of your enemies. Lasts $d.'),
    (993021, 0, 0, 0, 30, 30, 6, 6, 6, 1680, 3, 'Burnout', 'Infuses your pet with fury, greatly increasing its attack speed, damage and health for $d.'),
    (993022, 0, 0, 0, 15, 42, 6, 0, 0, 62, 2, 'Clarity', 'Clears your mind, greatly increasing mana regeneration for $d.'),
    (993023, 0, 0, 0, 12, 30, 6, 0, 0, 64, 1, 'Chloroplast', 'Nature knits your wounds, healing you every few seconds for $d.'),
    (993024, 0, 0, 0, 22, 41, 6, 6, 0, 543, 2, 'Incapacitate', 'Saps the target\'s strength, reducing attack power and Strength for $d.'),
    (993025, 0, 0, 0, 28, 0, 8, 0, 0, 212, 3, 'Theft of Thought', 'Steals a large amount of mana from the target and grants it to you.'),
    (993026, 0, 0, 0, 30, 5, 6, 0, 0, 55, 2, 'Malo', 'Curses the target, reducing all resistances by 200 for $d.'),
    (993027, 0, 0, 0, 40, 0, 9, 0, 0, 546, 4, 'Leech Touch', 'Tears the life from your target, transferring it to you.'),
    (993028, 0, 0, 0, 35, 85, 6, 0, 0, 64, 3, 'Promised Renewal', 'A promise of renewal that heals the target for 7500 after 18 seconds.'),
    (993029, 0, 0, 0, 28, 105, 6, 0, 0, 83, 3, 'Whirl til you Hurl', 'Spins the target helplessly, stunning it for $d.'),
    (993030, 0, 0, 0, 24, 23, 6, 0, 0, 98, 3, 'Invoke Fear', 'Strikes terror into the target, causing it to flee for $d.');
