-- Passive talents modifying the EQ spell pack (28_eq_spell_pack.sql).
-- GENERATED by tools/build_client_patch.py from tools/eq_talent_pack.json.
-- Do not edit by hand.
--
-- Each talent is a single-rank talent_dbc chain whose rank spell lives in
-- the patched Spell.dbc (client patch-P.mpq / server dbc/Spell.dbc). None
-- of these are in LOCKED_TALENTS, so they are purchasable with ordinary
-- Talent Points rather than Tome-of-Talents-only.

DELETE FROM `talent_dbc` WHERE `ID` BETWEEN 90001 AND 90999;
INSERT INTO `talent_dbc` (`ID`, `TabID`, `TierID`, `ColumnIndex`, `SpellRank_1`) VALUES
    (90001, 0, 3, 0, 994001),
    (90002, 0, 3, 0, 994002),
    (90003, 0, 3, 0, 994003),
    (90004, 0, 3, 0, 994004),
    (90005, 0, 4, 0, 994005),
    (90006, 0, 4, 0, 994006),
    (90007, 0, 4, 0, 994007),
    (90008, 0, 4, 0, 994008),
    (90009, 0, 8, 0, 994009),
    (90010, 0, 8, 0, 994010),
    (90011, 0, 8, 0, 994011),
    (90012, 0, 8, 0, 994012),
    (90013, 0, 5, 0, 994013),
    (90014, 0, 5, 0, 994014),
    (90015, 0, 5, 0, 994015),
    (90016, 0, 5, 0, 994016),
    (90017, 0, 4, 0, 994017),
    (90018, 0, 4, 0, 994018),
    (90019, 0, 4, 0, 994019),
    (90020, 0, 4, 0, 994020),
    (90021, 0, 6, 0, 994021),
    (90022, 0, 6, 0, 994022),
    (90023, 0, 6, 0, 994023),
    (90024, 0, 6, 0, 994024),
    (90025, 0, 9, 0, 994025),
    (90029, 0, 8, 0, 994029),
    (90030, 0, 8, 0, 994030),
    (90031, 0, 8, 0, 994031),
    (90032, 0, 8, 0, 994032);
