#!/usr/bin/env python3
"""Emit a `spell_dbc` override row that changes only the named fields.

The Phase 1d school-scoping passes (`broaden_talent_scoping.py`,
`school_scope_tier1.py`) rewrite whole rule sets; this tool is for the other shape
of fix: a handful of spells where one *field* is wrong, found while reviewing a
spec (see `.agents/plans/spec-design-review/FIXES.md`). Writing those rows by hand
is ~300 positional values per spell, which is how a migration silently reverts an
earlier pass's rewrite - so the row is always read out of the DBC this core loads
and re-emitted whole, with the named fields replaced.

Refusing to touch a spell that already has an override is deliberate: the DBC is
the *pre-override* row, so basing a new migration on it would undo whatever the
earlier pass changed (e.g. a school-scope conversion). Merge the change into that
pass's generator instead, or extend this tool to start from the DB row.

Text columns are emitted empty, which `DBCDatabaseLoader` reads as "not
overridden" (an empty column keeps the DBC's string), so names and tooltips
survive without resolving the string pool. `--set` therefore refuses text columns.

The header prose comes from `--why-file` (plain text; one comment line per line,
blank lines allowed) so the reasoning lives in the migration, not in a shell
history.

Usage:
  python3 tools/spell_dbc_override.py --spell 12042 --set SpellClassSet=0 \
      --why-file /tmp/why.txt --out ../../data/sql/updates/pending_db_world/rev_x.sql
  python3 tools/spell_dbc_override.py --spell 12042 --set SpellClassSet=0 --check
"""

import argparse
import os
import struct
import sys

MODULE_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(MODULE_ROOT, "tools"))

from build_client_patch import Dbc  # noqa: E402
from broaden_talent_scoping import (  # noqa: E402
    TABLE, TEXT_TYPES, load_columns, run_query, sql_values,
)

DEFAULT_DBC = os.path.join(MODULE_ROOT, "dbc", "Spell.dbc")

# Column index == DBC field index (the loader reads the row positionally). These
# anchors are checked on every run so a schema or field-order change fails loudly
# instead of writing a row into the wrong columns.
FIELD_ANCHORS = {"SpellClassSet": 208, "EffectAura_1": 95, "Name_Lang_enUS": 136}


def parse_sets(pairs):
    """{'Column': 'raw value'} from --set Column=Value, with the value kept as text."""
    out = {}
    for pair in pairs:
        if "=" not in pair:
            raise SystemExit(f"--set needs Column=Value, got {pair!r}")
        name, value = pair.split("=", 1)
        out[name] = value
    if not out:
        raise SystemExit("at least one --set is required")
    return out


def load_rows(dbc_path, ids):
    dbc = Dbc(dbc_path)
    rows = {}
    for index in range(dbc.recs):
        offset = index * dbc.recsize
        record_id = struct.unpack_from("<I", dbc.records, offset)[0]
        if record_id in ids:
            rows[record_id] = struct.unpack_from(f"<{dbc.fields}i", dbc.records, offset)
    missing = sorted(set(ids) - set(rows))
    if missing:
        raise SystemExit(f"not in {dbc_path}: {missing}")
    return rows


def apply_sets(row, columns, sets):
    """A copy of the DBC row with the named columns replaced."""
    index_of = {name: i for i, (name, _, _) in enumerate(columns)}
    out = list(row)
    for name, raw in sets.items():
        if name not in index_of:
            raise SystemExit(f"no such spell_dbc column: {name}")
        index = index_of[name]
        data_type, unsigned = columns[index][1], columns[index][2]
        if data_type in TEXT_TYPES:
            raise SystemExit(f"{name} is a text column; the loader keeps the DBC "
                             f"string for an empty one, so there is nothing to set")
        if data_type == "float":
            out[index] = struct.unpack("<i", struct.pack("<f", float(raw)))[0]
        elif unsigned:
            as_int = int(raw, 0)
            out[index] = as_int - (1 << 32) if as_int >= (1 << 31) else as_int
        else:
            out[index] = int(raw, 0)
    return out



def render_sql(rows, columns, sets, why, dbc_path):
    index_of = {name: i for i, (name, _, _) in enumerate(columns)}
    ids = sorted(rows)
    lines = []
    add = lines.append
    for line in why:
        add(f"-- {line}".rstrip())
    add("--")
    add("-- Generated by tools/spell_dbc_override.py from the DBC this core loads:")
    add(f"--   {dbc_path}")
    add("-- Fields changed: " + ", ".join(f"{n} = {v}" for n, v in sorted(sets.items())))
    add("-- Text columns are empty on purpose: the loader treats '' as 'not overridden',")
    add("-- so each spell keeps its own name and tooltip.")
    add("-- To revert, run this file's leading DELETE (it lists every id) and stop there.")
    add("")
    add(f"DELETE FROM `{TABLE}` WHERE `ID` IN ({', '.join(str(i) for i in ids)});")
    column_list = ", ".join(f"`{name}`" for name, _, _ in columns)
    add(f"INSERT INTO `{TABLE}`")
    add(f"  ({column_list})")
    add("VALUES")
    values = []
    for spell_id in ids:
        row = apply_sets(rows[spell_id], columns, sets)
        rendered = sql_values(row, columns, index_of["SpellClassSet"])
        values.append(f"  ({spell_id}, " + ", ".join(rendered[1:]) + ")")
    # The DELETE goes immediately above the INSERT (no blank line): the SQL
    # codestyle linter's safety rule requires the INSERT's previous line to carry
    # the DELETE. The file ends on the statement, not a blank line, for the same
    # reason.
    add(",\n".join(values) + ";")
    return "\n".join(lines) + "\n"


def check(rows, columns, sets):
    index_of = {name: i for i, (name, _, _) in enumerate(columns)}
    ids = sorted(rows)
    cols = ", ".join(f"`{n}`" for n in sorted(sets))
    live = {int(r["ID"]): r for r in run_query(
        f"SELECT ID, {cols} FROM `{TABLE}` WHERE ID IN ({', '.join(str(i) for i in ids)})")}
    bad = []
    for spell_id in ids:
        row = live.get(spell_id)
        if not row:
            bad.append((spell_id, "no override row"))
            continue
        want = apply_sets(rows[spell_id], columns, sets)
        for name in sorted(sets):
            if int(row[name]) != (want[index_of[name]] & 0xFFFFFFFF):
                bad.append((spell_id, f"{name}: DB {row[name]} != {want[index_of[name]]}"))
    if bad:
        print(f"DRIFT: {len(bad)} problem(s): {bad[:6]}", file=sys.stderr)
        return 1
    print(f"applied: {len(ids)} spell(s) carry the requested fields", file=sys.stderr)
    return 0


def main():
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--spell", type=int, action="append", required=True,
                        help="spell id to override (repeatable)")
    parser.add_argument("--set", action="append", default=[], metavar="COLUMN=VALUE",
                        help="field to change (repeatable)")
    parser.add_argument("--why-file", help="plain-text header for the migration")
    parser.add_argument("--out", help="SQL output path (omit with --check)")
    parser.add_argument("--check", action="store_true",
                        help="verify the live spell_dbc already has these values")
    parser.add_argument("--dbc", default=DEFAULT_DBC,
                        help=f"Spell.dbc to read (default: {os.path.relpath(DEFAULT_DBC, MODULE_ROOT)})")
    args = parser.parse_args()

    sets = parse_sets(args.set)
    columns = load_columns()
    for name, expected in FIELD_ANCHORS.items():
        index = next((i for i, (n, _, _) in enumerate(columns) if n == name), None)
        if index != expected:
            raise SystemExit(f"column layout changed: {name} is at {index}, expected {expected}")

    ids = sorted(set(args.spell))
    already = run_query(f"SELECT ID FROM `{TABLE}` WHERE ID IN ({', '.join(str(i) for i in ids)})")
    if already and not args.check:
        raise SystemExit("already overridden in the live DB (basing a new row on the DBC "
                         f"would revert that pass): {sorted(int(r['ID']) for r in already)}")

    rows = load_rows(args.dbc, set(args.spell))
    if args.check:
        return check(rows, columns, sets)
    if not args.out:
        raise SystemExit("--out is required unless --check")

    why = []
    if args.why_file:
        with open(args.why_file, encoding="utf-8") as handle:
            why = handle.read().rstrip("\n").split("\n")
    sql = render_sql(rows, columns, sets, why, args.dbc)
    with open(args.out, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(sql)
    print(f"wrote {args.out} ({len(sql) // 1024} KB, {len(rows)} spell(s))", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
